### ISSUE TITLE
Deprecation warning with Symfony 3.3's autowiring

### ISSUE THREAD

**Issue by ThomasLandauer** [endroid/QrCode#121]
When using the new autowiring feature of Symfony 3.3 - https://symfony.com/doc/current/service_container/3.3-di-changes.html - I get this deprecation warning:

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "endroid.qrcode.factory" service to "Endroid\QrCode\Factory\QrCodeFactory" instead.

I guess the referred `endroid.qrcode.factory` is the one that's being defined here: https://github.com/endroid/QrCode/blob/master/src/Bundle/Resources/config/services.yml#L2

**Comment by ThomasLandauer** [comment]
For the time being, you can add this to your `services.yml` to get rid of the warning:

```yml
services:
    # Remove Symfony 3.3 Deprecation Notice:
    Endroid\QrCode\Factory\QrCodeFactory:
        alias: "endroid.qrcode.factory"
```
